#!/usr/bin/env php
<?php

namespace Minion;

require('lib/config.base.php');
require('lib/minion.php');

try {
    require('config.php');
} catch (Exception $e) {
    die("Please copy config.php-dist to config.php, set your configuration variables, and re-run this script.");
}

$minion = new Minion();
$minion->run();

?>
